// flow-typed signature: 837fab571d888d068bb176c30658ac39
// flow-typed version: <<STUB>>/pg-then_v^1.2.1/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pg-then'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pg-then' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'pg-then/index' {
  declare module.exports: $Exports<'pg-then'>;
}
declare module 'pg-then/index.js' {
  declare module.exports: $Exports<'pg-then'>;
}
